// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqzoJWAxiWdtIqJrkKq8_CpeRSOSPP_xA',
    appId: '1:966946782511:web:d41e8e61c16ab47337b5da',
    messagingSenderId: '966946782511',
    projectId: 'ward-86a77',
    authDomain: 'ward-86a77.firebaseapp.com',
    storageBucket: 'ward-86a77.appspot.com',
    measurementId: 'G-44409F10Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE2jHi3iraNYVvvpbWMGYrkfAhilzw55U',
    appId: '1:966946782511:android:8c031239b12f7f2337b5da',
    messagingSenderId: '966946782511',
    projectId: 'ward-86a77',
    storageBucket: 'ward-86a77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASpuV2r9KJ2JVFsJ-PO2wOIJyoQwLed5g',
    appId: '1:966946782511:ios:7c7acb14978c1a6a37b5da',
    messagingSenderId: '966946782511',
    projectId: 'ward-86a77',
    storageBucket: 'ward-86a77.appspot.com',
    iosBundleId: 'com.example.ward',
  );
}
